name: 'Secrets: create or update environment secret'
description: Creates or updates a secret value on a repository environment
author: 'Peter Murray'

inputs:
  github_token:
    description: The GitHub token that has 'admin:org' permissions to access and modify secrets on the specified organization
    required: true

  repository:
    description: The full path to the repository to save the secret to
    required: true

  environment:
    description: The name of the environment
    required: true

  secret:
    description: The name of the secret to add or update
    required: true

  value:
    description: The value for the secret to be stored (will be encrypted using libsodium keys)
    required: true

  overwrite_existing:
    description: Flag to overwrite an existing secret
    default: true
    required: false

runs:
  using: node20
  main: '../dist/create-or-update-environment-secret/index.js'