# Docker Compose File for Application Container with Docker bindings
version: '3.8'

services:
  dev:
    image: ghcr.io/octodemo/development-containers/javascript-nodejs-20:base-202408-r2
    command: sleep infinity
    network_mode: host

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock